### ISSUE TITLE
PHPUnit alias breaking static analysis

### ISSUE THREAD

**Issue by precariouspanther** [colinmollenhour/credis#100]
This change: https://github.com/colinmollenhour/credis/commit/049ccfb2c680e4dfa6adcfa97f2f29d086919abd#diff-992f1596e0de7393cf7febdbdb934f65R4

which conditionally aliases the new PHPUnit TestCase to the old class name has broken static analysis such as typehinting and auto completion in Intellij/PHPStorm. Unfortunately these types of tools aren't intelligent enough to evaluate the conditional "only define if not already defined" so the `class_alias` is taking precedence over the original class definition.

**Comment by Xon** [comment]
There aren't very many good answers for this, I think giving up on old phpunit version may be the only real solution

**Comment by precariouspanther** [comment]
@Xon Unfortunately quite a few libraries have had to do this. Anyone who is still coupled to the older PHPUnit may just need to lock their composer to older versions of their libraries.
