### ISSUE TITLE
A warning is produced from the Client library

### ISSUE THREAD

**Issue by kanevbg** [colinmollenhour/credis#103]
Warning: Redis::expire() expects parameter 2 to be long, string given  in app/code/local/Credis/Client.php on line 1132

The project has both Cm RedisSession module and Cm Cache backend class. All the components are up to date (session module, session's module abstract library, cache backend, credis library). 

This is the configuration: [https://codebeautify.org/xmlviewer/cb1bb1d0](https://codebeautify.org/xmlviewer/cb1bb1d0)

I am trying to get a stack trace which will be published once I have. If any other information is needed I will try to provide.

**Comment by kanevbg** [comment]
I found the root cause. It was coming from module Lesti_FPC where the module was providing integer value by of type string. It will be great if the library can cast the value if php return true for "is_numeric"

**Comment by colinmollenhour** [comment]
Please provide a pull request since you already have the means to reproduce the issue. Thanks!
