### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by Nehace40** [colinmollenhour/credis#115]
Warning: Cannot modify header information - headers already sent by (output started at /srv/public_html/vendor/colinmollenhour/credis/Client.php:444) in /srv/public_html/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php on line 148

How to solve this issue?

**Comment by Nehace40** [comment]
Any update?

**Comment by colinmollenhour** [comment]
Sorry, not enough info or evidence of a bug in this library.
