### ISSUE TITLE
Magento can't connect to Redis after code deploy

### ISSUE THREAD

**Issue by CajuCLC** [colinmollenhour/credis#121]
We are using Magento on Kubernetes and after a code deploy we see that Magento can't connect to Redis and throws a bunch of errors:

```
Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/vendor/colinmollenhour/credis/Client.php on line 456
```
When we check Kubernetes we see that the Redis pod is running with no issues:

```
NAME                                         READY     STATUS             RESTARTS   AGE
...
redis-7775ccb875-gks89                       1/1       Running            0          30d
```

When we check Redis logs, there is no issue. The container can connect to Redis without issue.
Has anyone encountered something similar with Magento or any other application using `credis`?
Thank you!

**Comment by colinmollenhour** [comment]
This is just a library that opens a connection using PHP sockets or phpredis. If the connection doesn't work it is probably not a fault of this library.

**Comment by CajuCLC** [comment]
Just a note here since the issue was closed blaming whatever.
The connection was always up. It seems like the credis library has issues when you use DNS and the IPs change.
With Kubernetes the IPs can change quite quickly and credis is basically complaining about that.
I had the same issue with Magento 1. Changing the redis host from a DNS to an IP fixed in the past, unfortunately we can't do today.

**Comment by colinmollenhour** [comment]
Thanks for the update, that's great to know. However, DNS resolution is not handled by this library so I don't know what I can do.

I don't know of any DNS caching that happens within PHP, though. Are you sure the DNS is not being cached at another layer?

**Comment by CajuCLC** [comment]
Not that we are aware. The IP behind the DNS can and does changes at any time, maybe the library is not happy about that, but at least it can recover quickly and as far as I can tell it hasn't caused any issues so far.
