### ISSUE TITLE
$redis->ping() returns 1 with latest version of php-redis

### ISSUE THREAD

**Issue by daneren2005** [colinmollenhour/credis#122]
php-redis just was updated to 5.0.  Looking at the changelogs it looks like they made a change to make it so you can pass a param to ping:  `Allow PING to take an optional argument` (pulled from https://pecl.php.net/package-info.php?package=redis&version=5.0.0RC1).  When I don't pass anything with `$redis->ping()` it returns 1 now instead of `PONG`.  I am just going to start passing `PONG` in there to fix the issue for now, but there should not be an implicit 1 passed in ping.

**Comment by colinmollenhour** [comment]
Thanks for the report, would you mind submitting a PR?

**Comment by Xon** [comment]
I've opened a PR#123 with updated test environment to see what else breaks
