### ISSUE TITLE
Support for unlink method

### ISSUE THREAD

**Issue by xmorave2** [colinmollenhour/credis#126]
From version 4.0, Redis has an alternative DEL command called UNLINK, it would be nice to suppport it.

https://redis.io/commands/unlink

**Comment by colinmollenhour** [comment]
While it is not documented, I think it should just work since there are no special API requirements.

**Comment by joshua-bn** [comment]
For anyone wanting the async nature of UNLINK for DEL commands, you can enable that for all DEL commands in Redis config:

```
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
lazyfree-lazy-user-del yes
replica-lazy-flush yes
```

`lazyfree-lazy-user-del` is available in Redis 6.

**Comment by colinmollenhour** [comment]
Fixed in https://github.com/colinmollenhour/credis/commit/739183198fd4ff32728d025c12fcd8c62aa9ae6a
