### ISSUE TITLE
[Magento2] Function sentinel() not found in Credis_Client class

### ISSUE THREAD

**Issue by FirasGL** [colinmollenhour/credis#130]
Hello,

I'm trying to use this module to manage Magento2 cache in a Redis cluster (It's already supported in Magento2 core).
After adding sentinel_master parameter in my configuration and the list of redis servers, i'm blocked with a function called sentinel() in Credis_Client class **that does not exist**.
This function is called in many functions of Credis_Sentinel class : 

    public function masters()
    {
        return $this->_client->sentinel('masters');
    }
    /**
     * Return all information for slaves that are associated with a single master
     * @param string $name
     * @return mixed
     */
    public function slaves($name)
    {
        return $this->_client->sentinel('slaves',$name);
    }
    /**
     * Get the information for a specific master
     * @param string $name
     * @return mixed
     */
    public function master($name)
    {
        return $this->_client->sentinel('master',$name);
    }
    /**
     * Get the hostname and port for a specific master
     * @param string $name
     * @return mixed
     */
    public function getMasterAddressByName($name)
    {
        return $this->_client->sentinel('get-master-addr-by-name',$name);
    }
   /**
     * Perform an auto-failover which will re-elect another master and make the current master 
     * @param string $name
     * @return mixed
     */
    public function failover($name)
    {
        return $this->_client->sentinel('failover',$name);
    }

It throws this exceptions :

( ! ) Fatal error: Uncaught CredisException: unknown command 'sentinel' in /var/www/html/vendor/magento/zendframework1/library/Zend/Cache.php on line 209

( ! ) Zend_Cache_Exception: Unable to connect to a redis sentinel: unknown command 'sentinel' in /var/www/html/vendor/magento/zendframework1/library/Zend/Cache.php on line 209

Any ideas please ?
@colinmollenhour

**Comment by colinmollenhour** [comment]
The `Credis_Client` class uses a `__call` "magic method" so that any methods that are not declared are basically assumed to be valid redis commands and the response will be handled using the Redis standard data types. Note that only Redis running in sentinel mode recognizes the sentinel command so it sounds like maybe you're connecting to a normal redis instance.
