### ISSUE TITLE
New TLS support doesn't support versions in protocol identifier

### ISSUE THREAD

**Issue by waynetheisinger** [colinmollenhour/credis#133]
UseCase
---
To connect to Digital Ocean Redis Cluster

Description
---
If you don't include the tslv1.2:// protocol identifier then Digital Ocean throws a 
```error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length```

I've got a fix for this and will submit a PR

**Comment by colinmollenhour** [comment]
@wxiaoguang Yes, thanks!
