### ISSUE TITLE
Adding version constant

### ISSUE THREAD

**Issue by tillkruss** [colinmollenhour/credis#135]
We're implementing Credis with Redis Object Cache for WordPress and having a version number handy as part of the code would really helpful.

https://github.com/rhubarbgroup/redis-cache/pull/189

**Comment by colinmollenhour** [comment]
PR?

**Comment by tillkruss** [comment]
Will send 👍🏻

**Comment by colinmollenhour** [comment]
Thanks. I tagged 1.11.2
