### ISSUE TITLE
Provide Compatibility with PHP 8

### ISSUE THREAD

**Issue by norgeindian** [colinmollenhour/credis#156]
The function `Client.php::_prepare_comand` is not compatible with PHP 8.
The error message is the following: `Implode with arguments (array, string) call is deprecated since PHP 7.4 and removed since PHP 8.0`.
It would be awesome, if this compatibility could be provided.

**Comment by Xon** [comment]
Can you provide a stack trace with that error message?

**Comment by norgeindian** [comment]
@Xon , sorry, typo: the function is called `_prepare_command` in line 1477 of the current version.
I have no stack trace for that, I'm using PHP Code Sniffer with PHPCompatibility rule set to check the compatibility and there this issues arises.

**Comment by Xon** [comment]
This has been fixed since `v1.11.1` ( https://github.com/colinmollenhour/credis/releases/tag/1.11.1 )

**Comment by norgeindian** [comment]
@Xon , sorry, somehow did not see that. Thanks for your fast help.
