### ISSUE TITLE
[question] How to set redis options (such as serializer) ?

### ISSUE THREAD

**Issue by andrei-dascalu** [colinmollenhour/credis#157]
Hello,

Since Credis is a wrapper, I'm wondering if:

- there's a way to provide a preconfigured client?
- alternatively, is there a way to execute setOpt to set things like serialization? (I need a way to be able to ask for igbinary when available).

Thanks

**Comment by colinmollenhour** [comment]
Hi @andrei-dascalu it sounds like you could do these things by simply extending `Credis_Client` with your own wrapper?
