### ISSUE TITLE
Socket connection error in PHP 8.1: deprecated parameter type

### ISSUE THREAD

**Issue by JosephLeedy** [colinmollenhour/credis#159]
## Expected Result

The library connects to Redis successfully through the local socket.

## Actual Result

The following error is thrown: `Deprecated: Redis::connect(): Passing null to parameter #2 ($port) of type int is deprecated in vendor/colinmollenhour/credis/Client.php on line 477`.

## Notes

Connecting through 127.0.0.1 works properly.

## Environment

- macOS 12.1.0
- PHP 8.1.13
- Credis v1.12.1 
- phpredis 5.3.7
- Redis 6.2.6
- Adobe Commerce 2.4.4-beta4

## Configuration
- host: `unix:///usr/local/var/run/redis.sock`
- port: `6379`
- database: `8`
- password: `''`

**Comment by JosephLeedy** [comment]
@colinmollenhour any idea of when a new version with this fix will be tagged?

**Comment by colinmollenhour** [comment]
@JosephLeedy I just tagged a new release.

**Comment by JosephLeedy** [comment]
Thanks!
