### ISSUE TITLE
Credis_Client port issues ?

### ISSUE THREAD

**Issue by Nuranto** [colinmollenhour/credis#166]
Here is the `Credis_Client` constructor : 

```
public function __construct($host = '127.0.0.1', $port = 6379, $timeout = null, $persistent = '', $db = 0, $password = null)
    {
        $this->host = (string) $host;
        $this->port = (int) $port;
```

As you can see, the `$port` is casted to `int`.

In https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/master/Cm/Cache/Backend/Redis.php#L181, you're calling that constructor with `NULL` for `$port`, which leads the lib to try to connect to `host-name:0`. Or `host-name:26379:0` (cf below).

Also, could be great to manage in that constructor hostnames that includes port. For instance `host-name:1234`, and null port should result to `$host` => `host-name` and `$port` => `1234`.  The issue is that the sentinel servers variable asks for a list of servers, comma separated, so we may have to set the port in this format. And there is no other way to set the sentinel port (that's why you used `NULL` in the link above).
That format would be supported without the `int` cast (see code below). However, it would be more safe and clean to populate both variables. 

```
$remote_socket = $this->port === NULL
                ? $this->scheme.'://'.$this->host
                : $this->scheme.'://'.$this->host.':'.$this->port;
```

But maybe I miss something here, since it seems I'm the first one to report this...  If not, I can propose you a MR if you want, tell me.

(I'm running with standalone)

**Comment by Xon** [comment]
A work-around is the list of sentinel(s_ can have the actual port added as part of the host string. ie "tcp://127.0.0.1:26379". This will bypass this bug.

Cm_Cache_Backend_Redis really should be passing in the port `26379` and not `null`.

**Comment by Nuranto** [comment]
We do add the port to host string, which leads to `127.0.0.1:26379:0` because `$this->port` is not null (look at the code above).

**Comment by colinmollenhour** [comment]
Thanks for the report. #167 has been merged and new release tagged.

> I still think that class should be refactored regarding the scheme/port/host management
I don't love the constructor but it isn't worth breaking BC for, unfortunately.
