### ISSUE TITLE
PHP 8.2 Use of self in callables is deprecated

### ISSUE THREAD

**Issue by luigifab** [colinmollenhour/credis#170]
Perhaps I'm wrong, but I tried PHP 8.2.0-rc5 with [`lib/Credis/Client.php`](https://github.com/OpenMage/magento-lts/blob/1.9.4.x/lib/Credis/Client.php) provided by OpenMage and [`Client.php`](https://github.com/colinmollenhour/credis/blob/master/Client.php) of this repository, and I get one deprecation (with Sentry):

![image](https://user-images.githubusercontent.com/31816829/200314906-f5b95ec6-d344-483d-87c0-cbbc03af7a54.png)

Not sure what is the right fix.

**Comment by Xon** [comment]
The fix is fairly simple: `'self'` => `self::class`

**Comment by Xon** [comment]
Fixed in #171

**Comment by colinmollenhour** [comment]
Merged and tagged as 1.14.0
