### ISSUE TITLE
Suggest to remove `define('CRLF')` or use a const for it

### ISSUE THREAD

**Issue by wxiaoguang** [colinmollenhour/credis#172]
At the moment, the definition of CRLF seems not ideal: https://github.com/colinmollenhour/credis/blob/master/Client.php#L23

There are only a few usages of the `CRLF` const.

IMO maybe all CRLF in code could be replaced by literal string `"\r\n"`

Or, use modern PHP way: `const CREDIS_CRLF = "\r\n"`.

(I could help to propose a PR)

**Comment by colinmollenhour** [comment]
No objections

**Comment by wxiaoguang** [comment]
-> Use const keyword instead of define function for CRLF #174
