### ISSUE TITLE
Best practise to add a new command name.

### ISSUE THREAD

**Issue by toonvd** [colinmollenhour/credis#184]
When using credis to create a KeyDB driver, I ran into errors that the command does not exist, using PHPRedis Rawcommand, there is no isseue.
I am trying to call `EXPIREMEMBER` to expire members of a hash (making set cleanup redundant).
A function is not available so I tried going through `exec` but the command resulted in `null`.
Should I add this command to commandNames before calling exec? Or would you accept a PR for a function specifically for expiremember?

Thanks in advance!

**Comment by colinmollenhour** [comment]
In standalone mode it should be possible to call any command as a method name, but if there is a command that PHPRedis does not support then you will need to add some override code. For example, transform `expireMember` to `rawCommand` in the `__call` method.

Alternatively, get PHPRedis to add support for `expireMember`.

**Comment by Xon** [comment]
This should work with both phpredis and standalone mode:
```php
$credis->rawCommand('expireMember', [$key, $subkey]);
```

PHPRedis's policy is to only support official redis commands and not ones implemented in keydb/dragonflydb/etc

**Comment by colinmollenhour** [comment]
Thanks for the insight, @Xon !

**Comment by toonvd** [comment]
Hi @Xon sorry for replying so late but life got in the way. Thanks for the help! Already implemented it that way!
