### ISSUE TITLE
Random Magento exception: Failed to write entire command to stream from Credis/Client.php

### ISSUE THREAD

**Issue by VladanZ** [colinmollenhour/credis#29]
Using Redis and Credis Client.php library without phpredis installed and Magento 1.9 issues random exception: Failed to write entire command to stream";i:1;s:3418:"#0 /path-to-magento-folder/lib/Credis/Client.php(537): Credis_Client->write_command('*2??$6??select?...').
This event is random and causes the site to show ugly Magento Exception report page. After the reload the page is shown, but the error appears on random page every now and then.

I managed to install and activate phpredis and this problem no longer exists, so the problem is probably just with the PHP standalone version.

**Comment by colinmollenhour** [comment]
@scoolen and @VladanZ Did this fwrite-retry branch fix your issue?

**Comment by VladanZ** [comment]
Yes, I have no more problems after fix.

2015-12-17 18:19 GMT+01:00 Colin Mollenhour <notifications@github.com>:

**Comment by colinmollenhour** [comment]
Merged the fix branch.
