### ISSUE TITLE
CredisException: ERR MULTI calls can not be nested

### ISSUE THREAD

**Issue by goallin** [colinmollenhour/credis#35]
Hi Colin,

```
I use credis with phpredis, when invoke a unwatch after exec command, I got a CredisException saying "ERR MULTI calls can not be nested";
```

redisLib::instance()->watch("foo");
$reply = redisLib::instance()->multi(Redis::MULTI)
    ->set('foo', 1)
    ->set('bar', 1)
    ->exec();
redisLib::instance()->unwatch();

I guess we need a return after send "multi" to phpredis, otherwise we'll send second multi command to phpredis some lines after.
Please advise if I misunderstand something, thank you.

// Proxy pipeline mode to the phpredis library
if($name == 'pipeline' || $name == 'multi') {
    if($this->isMulti) {
        return $this;
    } else {
        $this->isMulti = TRUE;
        $this->redisMulti = call_user_func_array(array($this->redis, $name), $args);
        return $this;  // need a return here
    }
}

// Multi and pipeline return self for chaining
if($this->isMulti) {
    call_user_func_array(array($this->redisMulti, $name), $args);
    return $this;
}

**Comment by colinmollenhour** [comment]
I'm not sure if I understand the issue.. Please submit a PR if you think you know the solution. Thanks!

**Comment by Xon** [comment]
@colinmollenhour this was fixed in https://github.com/colinmollenhour/credis/issues/57 by https://github.com/colinmollenhour/credis/commit/74b2b703da5c58dc07fb97e8954bc63280b469bf
