### ISSUE TITLE
getSelectedDb not working on Cluster auto-selectable Client

### ISSUE THREAD

**Issue by Horrower** [colinmollenhour/credis#40]
$oSentinel = new \Credis_Sentinel(new \Credis_Client($host, $port));

$oRedisInstance = $oSentinel->getCluster($sSentinelName, $db);

$oRedisInstance->getSelectedDb() // -- will throw error: 
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Redis' does not have a method 'getselecteddb' in .../vendor/colinmollenhour/credis/Client.php on line 1047

But, when you create standalone Client - it works find.
$oRedisInstance = new \Credis_Client($host, $port);
$oRedisInstance->select($db);
$oRedisInstance->getSelectedDb() // -- works find

It's because Cluster->__call takes Client and run __call on it, which NOT try check if method present and trying to run Redis command.
Please, add somewhere in __call something like that:
if (method_exists($this,$name) {
   return $this->{$name}();
}

**Comment by colinmollenhour** [comment]
Thanks for the report.
