### ISSUE TITLE
scan returns false for last set of matches

### ISSUE THREAD

**Issue by rupaschomaker** [colinmollenhour/credis#42]
redis returns the following for a small set of matches:

```
127.0.0.1:6379> "scan" "0" "MATCH" "table service *"
1) "0"
2) 1) "table service parms {\"server_id\":\"2\"}"
   2) "table service parms {\"server_id\":\"9\"}"
```

Since the cursor matches empty() for the response is set to false rather than returning the response array.  I don't have an easy patch to fix this that results in compatible behavior.

This will also happen if one has multiple "pages" of data since the last one will have a cursor of "0" to let the caller know that the result has no more.

**Comment by Xon** [comment]
@colinmollenhour this should be resolved as of https://github.com/colinmollenhour/credis/pull/65
