### ISSUE TITLE
read error on connection

### ISSUE THREAD

**Issue by jpruiz114** [colinmollenhour/credis#43]
Hello, I'm having this error in a production server:

Fatal error: Uncaught exception 'RedisException' with message 'read error on connection' in /.../lib/Credis/Client.php:843 

Has it happened to any of you?

**Comment by colinmollenhour** [comment]
I don't think this is a bug, but rather an issue with the server just not responding for some reason. E.g. while it is doing a blocking command like eval. Could also be a network issue, Redis bug, etc.
