### ISSUE TITLE
No Support for multiple sentinels

### ISSUE THREAD

**Issue by jonas-balius** [colinmollenhour/credis#46]
Following "Guidelines for Redis clients with support for Redis Sentinel" ( http://redis.io/topics/sentinel-clients ):
"A Redis client supporting Sentinel can automatically discover the address of a Redis master from the master name using Redis Sentinel. So instead of a hard coded IP address and port, a client supporting Sentinel should optionally be able to take as input:
    \* A list of ip:port pairs pointing to known Sentinel instances."

This sentinel client accepts only one client.

Because of that this sentinel client will not be able to find a redis master if selected sentinel fails:

"Step 1: connecting to the first Sentinel

The client should iterate the list of Sentinel addresses. For every address it should try to connect to the Sentinel, using a short timeout (in the order of a few hundreds of milliseconds). On errors or timeouts the next Sentinel address should be tried.

If all the Sentinel addresses were tried without success, an error should be returned to the client."

**Comment by colinmollenhour** [comment]
Hi Jonas,

While you are right that it only accepts one client, I don't see why you couldn't do something like the following:

```php
function getSentinel($sentinelHosts) {
    foreach (explode(',',$sentinelHosts) as $sentinelHost) { // Sort or randomize as appropriate
        try {
            $client = new Credis_Client($sentinelHost, NULL, 0.1);
            $client->connect();
            return new Credis_Sentinel($client);
        } catch (CredisException $e) {}
    }
    throw new Exception("Could not connect to a Redis sentinel.");
}
```

There are a lot of ways that a user might want to do this differently, such as the order of connection attempts, retries, varying timeouts, logging specific errors, etc. So while there could certainly be a method somewhere in the official library for this it is not so terrible IMO to roll your own.

However, as always I welcome pull requests if you have a good solution. Perhaps even if we just add the above as an example to the README. Let me know your thoughts.
