### ISSUE TITLE
Do not throw an exception when calling forceStandalone and standalone is already the case

### ISSUE THREAD

**Issue by tsteur** [colinmollenhour/credis#52]
In https://github.com/colinmollenhour/credis/issues/46#issuecomment-157817598 it was suggested to use sentinel with multiple servers for example like this:

```php
function getSentinel($sentinelHosts) {
    foreach (explode(',',$sentinelHosts) as $sentinelHost) { // Sort or randomize as appropriate
        try {
            $client = new Credis_Client($sentinelHost, NULL, 0.1);
            $client->connect();
            return new Credis_Sentinel($client);
        } catch (CredisException $e) {}
    }
    throw new Exception("Could not connect to a Redis sentinel.");
}
```

I tested it and it my tests fail with this implementation. Problem is that Sentinel calls `$client->forceStandalone()` in https://github.com/colinmollenhour/credis/blob/1.6/Sentinel.php#L53 but the client is already connected causing it to trigger an exception in https://github.com/colinmollenhour/credis/blob/1.6/Client.php#L361 `Cannot force Credis_Client to use standalone PHP driver after a connection has already been established.`

Instead in the `forceStandalone` method of the client it should be checked in the beginning whether standalone is already the case and if so, return immediately:

```php
    public function forceStandalone()
    {
        if ($this->standalone) {
            return $this;
        }

        if($this->connected) {
        ...
```

**Comment by colinmollenhour** [comment]
Thanks, Thomas!
