### ISSUE TITLE
In composer.json PHP 5.3 is required, but PHP 5.4 is needed actually

### ISSUE THREAD

**Issue by tsteur** [colinmollenhour/credis#56]
See https://github.com/colinmollenhour/credis/blob/master/Cluster.php#L194 where an array is created via `[]`. This requires PHP 5.4+.

However, in composer.json https://github.com/colinmollenhour/credis/blob/master/composer.json#L14 PHP 5.3 is required.

**Comment by colinmollenhour** [comment]
Good observation. Thanks!
