### ISSUE TITLE
Pipeline called twice

### ISSUE THREAD

**Issue by cbrews** [colinmollenhour/credis#57]
Hey,

I'm running into an issue when I'm using credis with some PHP instrumentation (specifically, we're using TraceView).  Hoping you can help troubleshoot.  We are using your Cm_RedisSesion Magento module, which leverages this lib.

The problem we are seeing is within the `__call()` method when calling a pipeline.

When we call the credis `pipeline()` function, in the call function, the internal redis->pipeline call is happening twice without closing the connection.  At the beginning, $this->isMulti is set to false, so `call_user_func_array` is calling `pipeline`.

```
    // Proxy pipeline mode to the phpredis library
    if($name == 'pipeline' || $name == 'multi') {
        if($this->isMulti) {
            return $this;
        } else {
            $this->isMulti = TRUE;
            $this->redisMulti = call_user_func_array(array($this->redis, $name), $args); 
        }
    }
```

Then the code continues (there is no return after call_user_func_array), and it later executes this:

```
    // Multi and pipeline return self for chaining
    if($this->isMulti) {
        call_user_func_array(array($this->redisMulti, $name), $args);
        return $this;
    }
```

Since it's making two calls to pipeline in one session, it's breaking our instrumentation (not sure on exactly why, I don't have a lot of details from TraceView except that they said if you invoke a pipeline without calling 'exec()' on it, leaving it open, that there's an issue, and exec() is called after __call() is invoked).

Our immediate resolution is going to be adding a `return $this` after the first call to pipeline.  But I wanted to run this by you to see if you think this will be problematic.  Let me know if I can provide more details.

**Comment by colinmollenhour** [comment]
Hi Chris, thanks for the detailed bug report. I believe you are absolutely right and your fix is also correct. It is amazing that it took over 4 years for this bug to be found, but a bug is a bug. :)
Tagged as 1.7
