### ISSUE TITLE
It would be better to add the dependency as a composer dependency to their package

### ISSUE THREAD

**Issue by yssource** [colinmollenhour/credis#58]
"post-update-cmd" do not git pull the lib/Credis if using the installer "Cotya/magento-composer-installer
".
It would be better to add the dependency as a composer dependency to their package. #https://github.com/Cotya/magento-composer-installer/issues/104

**Comment by colinmollenhour** [comment]
As Credis is just a dependency I think the proper place to discuss is the other ticket or a new ticket on Cm_Cache_Backend_Redis
