### ISSUE TITLE
No support for ZUNIONSTORE

### ISSUE THREAD

**Issue by consolibyte** [colinmollenhour/credis#69]
It doesn't look like there's any support for this Redis command:
http://redis.io/commands/zunionstore

Or at least I couldn't find any examples of how to use it?

**Comment by colinmollenhour** [comment]
If it isn't documented then it likely works with the magic methods already in place but not necessarily. Without any special attention to a particular method the standalone mode will just flatten all arguments and send the request and return the response. In some cases special handling of arguments is needed, especially to make it 100% compatible with the phpredis library (if you have this installed but want to not use it then use `forceStandalone()` to bypass it).

So I suggest just giving it a try and see if it works. I'd be happy to accept a PR for any improvements to vardocs or special handling for 100% support of new methods.

**Comment by consolibyte** [comment]
Thanks, tested and bumped into some issues. Created a PR request with the fixes -- PR #75.
