### ISSUE TITLE
Cluster with failover?

### ISSUE THREAD

**Issue by tegansnyder** [colinmollenhour/credis#70]
Is it possible to configure the library to allow failovers when a alias is unreachable? My master server is really just a HAProxy endpoint that is configured to check the health checks of my slave instances and promote a new master when one fails. See thread here for details: https://karlstoney.com/2015/07/23/redis-sentinel-behind-haproxy/

Here is my current configuration:

```php
        $this->redis = new \Credis_Cluster(
            [
                [
                    'host' => '10.10.10.1', // HAProxy checking Sentinel tcp health checks and promoting new master if failure occurs
                    'port' => 26379,
                    'alias' => 'master',
                    'master' => true,
                    'password' => 'something',
                ],
                [
                    'host' => '10.10.10.2',
                    'port' => 6379,
                    'alias' => 'slave-1',
                    'password' => 'something',
                ],
                [
                    'host' => '10.10.10.3',
                    'port' => 6379,
                    'alias' => 'slave-2',
                    'password' => 'something',
                ],
                [
                    'host' => '10.10.10.4',
                    'port' => 6379,
                    'alias' => 'slave-3',
                    'password' => 'something',
                ],
                [
                    'host' => '10.10.10.5',
                    'port' => 6379,
                    'alias' => 'slave-4',
                    'password' => 'something',
                ],
            ]
        );
```

It would be nice if the alias servers could failover, right now they throw a `CredisException` if they are unreachable.

I see phpredis has a few options that might work, but I'm wondering if you have tried them:
```
->setOption(RedisCluster::OPT_SLAVE_FAILOVER, RedisCluster::FAILOVER_DISTRIBUTE);
```

Thanks

**Comment by colinmollenhour** [comment]
I haven't tried them.. However, not sure if I really want to go that route (building Redis high availability logic into the application or library). I recently started using Sentinel myself and in my setup the HAProxy instances do the health checks against the redis servers, not the sentinels and they require a node to be "role:master". In this way the HAProxy instances will always direct traffic to the master and the clients simply connect directly to HAProxy and do not need to be sentinel-aware. The sentinels can be ignored by the client application entirely, although they are still useful for automating the cluster initialization and failover. 

```
defaults
  mode tcp
  timeout client     1h
  timeout server     1h
  timeout connect 1000

frontend redis-tcp
  bind *:6379
  default_backend redis

# The tcp-check will ensure that only reachable master nodes are considered "up". 
backend redis
  balance first
  option tcplog
  option tcp-check
  tcp-check send info\ replication\r\n
  tcp-check expect string role:master
  default-server inter 5000 downinter 5000 fastinter 1000 rise 2 fall 3 maxconn 256 maxqueue 128
  {{HOSTS}}
  server node${num} ${ip}:6379 check
  {{/HOSTS}}
```

The {{HOSTS}} part renders one line per server. See https://github.com/colinmollenhour/haproxy-service

**Comment by tegansnyder** [comment]
Hi @colinmollenhour,

Thanks for your reply. I'm trying to understand your configuration. It appears you are instructing HAProxy to do health-checks against the Redis master servers. 

I have a similar HAProxy configuration, it looks as follows:
```
defaults
	mode tcp
	timeout connect 4s
	timeout server  30s
	timeout client  30s

frontend redis-tcp
	bind *:26379 name redis
	default_backend redis-alpha

backend redis
	option tcp-check
	tcp-check send AUTH\ OMMITED_REDIS_PWD\r\n
	tcp-check send PING\r\n
	tcp-check expect string +PONG
	tcp-check send info\ replication\r\n
	tcp-check expect string role:master
	tcp-check send QUIT\r\n
	tcp-check expect string +OK
	server redis-1 X.X.X.1:6379 maxconn 1024 check inter 1s
	server redis-2 X.X.X.2:6379 maxconn 1024 check inter 1s
	server redis-3 X.X.X.3:6379 maxconn 1024 check inter 1s
	server redis-4 X.X.X.4:6379 maxconn 1024 check inter 1s
	server redis-5 X.X.X.5:6379 maxconn 1024 check inter 1s
```

After reading your reply, I'm trying to understand if your configuration allow slaves? The ideal scenario would be to utilize the slaves for high availability/load balancing and the master for writes. When health check fails on a master a new master is promoted.

Can you share an example your `sentinel.conf`?

Thanks!

**Comment by colinmollenhour** [comment]
My HAProxy does health checks against all redis nodes, but not redis sentinels. It only considers the master node to be up and considers all others to be down. I'm only going for redundancy but if you wanted to also go for load balancing reads I would recommend having two HAProxy backends, one for writes (only the master is up) and one for reads (all nodes that are part of the replication).

**Comment by tegansnyder** [comment]
Good call on two backends, that is going to be what I do. Thanks Colin, much appreciated.
