### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by elberth90** [colinmollenhour/credis#71]
Hey,

I have one question connected with tests, are they valid? I'm trying to dockerize them, but for example I get segmentation fault during `testPubsub` and many other errors.

**Comment by Xon** [comment]
Segmentation fault means you are likely hitting bugs in phpredis somewhere.

credis itself should in no way cause segfaults in a sane php setup.

**Comment by elberth90** [comment]
My questions is more about, does someone run this tests recently, and they passed?

**Comment by colinmollenhour** [comment]
I haven't run them recently. However, as Xon mentioned, segfaults are not a bug in PHP code but in some compiled component of PHP.
