### ISSUE TITLE
Poor behavior when a sentinel's connection is garbled

### ISSUE THREAD

**Issue by Xon** [colinmollenhour/credis#76]
In a VM; using persistent connections with the Credis_Sentinel works reasonably well until a "Unable to connect to a redis sentinel: Read operation timed out." occurs due a high cpu steal spike from the host.

Stack trace
```
Zend_Cache_Exception: Unable to connect to a redis sentinel: Read operation timed out. - library/Zend/Cache.php:209
#0 library/Redis/Cm/Cache/Backend/Redis.php(208): Zend_Cache::throwException('Unable to conne...', Object(CredisException))
#1 library/Zend/Cache/Backend/Redis.php(20): Cm_Cache_Backend_Redis->__construct(Array)
#2 library/Zend/Cache.php(153): Zend_Cache_Backend_Redis->__construct(Array)
#3 library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Redis', Array, false, false)
```

Then alternating these exceptions:
```
CredisException: Can' retrieve slave status - library/Redis/lib/Credis/Sentinel.php:168
#0 library/Redis/lib/Credis/Sentinel.php(185): Credis_Sentinel->createSlaveClients('mymaster')
#1 library/Redis/Cm/Cache/Backend/Redis.php(213): Credis_Sentinel->getSlaveClients('mymaster')
#2 library/Zend/Cache/Backend/Redis.php(20): Cm_Cache_Backend_Redis->__construct(Array)
#3 library/Zend/Cache.php(153): Zend_Cache_Backend_Redis->__construct(Array)
#4 library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Redis', Array, false, false)
```
and
```
ErrorException: Array to string conversion - library/Redis/lib/Credis/Client.php:300
#0 library/Redis/lib/Credis/Client.php(300): XenForo_Application::handlePhpError(8, 'Array to string...', '/var/www/sites/...', 300, Array)
#1 library/Redis/lib/Credis/Sentinel.php(139): Credis_Client->__construct(Array, Array, 1, 0, 0, NULL)
#2 library/Redis/lib/Credis/Sentinel.php(150): Credis_Sentinel->createMasterClient('mymaster')
#3 library/Redis/Cm/Cache/Backend/Redis.php(184): Credis_Sentinel->getMasterClient('mymaster')
#4 library/Zend/Cache/Backend/Redis.php(20): Cm_Cache_Backend_Redis->__construct(Array)
```

This lasts for a while for a minute or so till the Sentinel hangs up.

It looks like the persistent connection still has data on it, so it fails to close. Some advice recommends calling fclose() on persistent connections if they are in a broken state to force php to discard them.

I think replacing calls to ```$this->connected = FALSE;``` with ```$this->close(true);```, using https://github.com/Xon/credis/commit/c6d67184c1c49f9d6f64e927e87715cf49b327e6 with a 'force' parameter. 

It ensures the close() function invalidates any pipelining when in standalone mode otherwise calling close() and then then reconnect gets the Credis into a confused state.

I haven't yet deployed the latest commit on the connection_retry branch, but plan to after a little more testing.

**Comment by Xon** [comment]
Looking into read_command function, it explicitly doesn't try to disconnect on a timeout and leaves the recovery to the next write_command IIF the connection has ended. The read-timeout means the syscall stops blocking early; not that the TCP connection itself has timed out.

This means the connection be in a weird state where there is more data on the wire than is expected.

With persistent connection, this obviously gets worse as it can affect many requests with the same connection.

I would think attempting to close a connection on any sort of network error would be the sane approach, unless there is a better way todo recovery.

@colinmollenhour thoughts?

**Comment by colinmollenhour** [comment]
Your explanation and suggested fix make sense and I can't think of a better way to handle connection errors than explicitly closing the connection without adding a lot of complexity. Nice work!

**Comment by Xon** [comment]
The improved retry logic should fix this :)
