### ISSUE TITLE
Connect retries not attempted with phpredis

### ISSUE THREAD

**Issue by sshymko** [colinmollenhour/credis#81]
**Environment:**
- PHP 7.0.18
- [phpredis](https://github.com/phpredis/phpredis) 3.1.2

**Steps to reproduce:**
1. Make sure the Redis server `127.0.0.1:6379` is unresponsive (or not running at all)
1. Execute the following test script:
```php
$redis = new Credis_Client('127.0.0.1', 6379, $timeout = 2.5);
$redis->setMaxConnectRetries(3);
$redis->connect();
```

**Expected result:**
- Three unsuccessful connection attempts
- Exception `CredisException` with the following message is thrown:
> Connection to Redis failed after 3 failures.

**Actual result:**
- One unsuccessful connection attempt
- Error `E_WARNING` with the following message is triggered:
> Redis::connect(): connect() failed: Connection timed out

**Comment by sshymko** [comment]
FYI: The original test case involves Magento 2.1.4 shipped with the `Redis_Client` library.

**Comment by colinmollenhour** [comment]
I believe that should have been fixed by the recently cherry-picked commit from #73. (4d6b94386662f86827f74426ecab073a0a17242d)

**Comment by sshymko** [comment]
@colinmollenhour 
Thanks for your reply.
It is definitely worth trying out the referenced changes.

However, I don't see other way around `E_WARNING` other than silencing `$this->redis->connect()` via the `@` operator or `set_error_handler()`, but #73 does not use these techniques.

**Comment by colinmollenhour** [comment]
IIRC Magento already uses set_error_handler and essentially converts errors into exceptions so catching the exception should silence the warning. But I could be wrong.. :)

**Comment by sshymko** [comment]
Thanks, @colinmollenhour, that should work!

Really struggling to upgrade the Redis dependencies on Magento 2.1.4 installed via Composer.
The Magento package declares dependencies on exact (and outdated) versions.
Any recommendation how to overcome that?

**Comment by sshymko** [comment]
@colinmollenhour 
Looks like #73 has not been released yet. When are you going to tag the release version?

**Comment by colinmollenhour** [comment]
I just tagged 1.8.2 and also updated the cache and session backends for those using modman.

**Comment by sshymko** [comment]
Thanks @colinmollenhour !
Will upgrade the library and test whether that resolves the timeout issue for us.
Will keep you posted on the results.
