### ISSUE TITLE
Pipeline returns different result format for HMGET in standalone/redis extension mode

### ISSUE THREAD

**Issue by maff** [colinmollenhour/credis#84]
When executing HMGET over a pipeline, the result is different in standalone and Redis extension mode. While a simple HMGET always returns an array with numeric indexes in both standalone and Redis extension mode, the HMGET over a pipeline with the Redis extension enabled returns an array indexed by field name instead. See the following test case (the `myhash` has is the one from https://redis.io/commands/hmset):

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$id     = 'myhash';
$fields = ['field1', 'field2'];

$redis = new Credis_Client('127.0.0.1', 6379, null, '', 13);

if (extension_loaded('redis')) {
    echo "The Redis extension is loaded\n\n";
} else {
    echo "The Redis extension is not loaded\n\n";
}

// simple hMGet
echo "Simple HMGET\n";
var_dump($redis->hMGet($id, $fields));
echo "\n";

// pipeline HMGET
echo "Pipeline HMGET\n";

$pipeline = $redis->pipeline()->multi();
$pipeline->hMGet($id, $fields);
var_dump($pipeline->exec()[0]);
```

Without Redis extension:

```shell
The Redis extension is not loaded

Simple HMGET
/home/vagrant/credis-index/credis-test.php:18:
array(2) {
  [0] =>
  string(5) "Hello"
  [1] =>
  string(5) "World"
}

Pipeline HMGET
/home/vagrant/credis-index/credis-test.php:26:
array(2) {
  [0] =>
  string(5) "Hello"
  [1] =>
  string(5) "World"
}
```

With Redis extension (see Pipeline HMGET):

```shell
The Redis extension is loaded

Simple HMGET
/home/vagrant/credis-index/credis-test.php:18:
array(2) {
  [0] =>
  string(5) "Hello"
  [1] =>
  string(5) "World"
}

Pipeline HMGET
/home/vagrant/credis-index/credis-test.php:26:
array(2) {
  'field1' =>
  string(5) "Hello"
  'field2' =>
  string(5) "World"
}
```

PHP version: PHP 7.1.6
Redis extension version: 3.1.2
Redis version: 3.2.8
colinmollenhour/credis: 1.8.2

**Comment by Xon** [comment]
I would recommend testing against the raw [phpredis](https://github.com/phpredis/phpredis) extension to verify it's behaviour. Because if it is behaving differently in pipeline vs non-pipeline mode you'll need to file a bug with the phpredis extension project

**Comment by maff** [comment]
The problem is that credis' responses are inconsistent in standalone/non-standalone mode. phpredis always returns an array which is indexed by field name while credis does always return an array with numeric indexes with the exception of the pipelined HMGET with the redis extension (1 out of 4 possibilities returns a different format): 

* phpredis: fieldname
* phpredis pipelined: fieldname
* credis standalone: numeric
* credis pipelined standalone: numeric
* credis redis: numeric
* credis pipelined redis: fieldname

Updated test case taking phpredis into account: https://gist.github.com/maff/a1f6a685ee29daaa9958ab0796a3688a

## Redis disabled
```shell
$ php credis-test.php
DEBUG: credis version: 1.8.2@9c14b4bb0779127638a17dd8aab8f05f28c6df43
DEBUG: The Redis extension is not loaded

credis: simple HMGET
Array
(
    [0] => Hello
    [1] => World
)

credis: pipeline HMGET
Array
(
    [0] => Hello
    [1] => World
)
```

## Redis enabled

```shell
$ php -dextension=redis.so credis-test.php
DEBUG: credis version: 1.8.2@9c14b4bb0779127638a17dd8aab8f05f28c6df43
DEBUG: The Redis extension is loaded

phpredis: simple HMGET
Array
(
    [field1] => Hello
    [field2] => World
)

phpredis: pipeline HMGET
Array
(
    [field1] => Hello
    [field2] => World
)

credis: simple HMGET
Array
(
    [0] => Hello
    [1] => World
)

credis: pipeline HMGET
Array
(
    [field1] => Hello
    [field2] => World
)
```

**Comment by Xon** [comment]
@maff can you test https://github.com/colinmollenhour/credis/pull/86 to see if it fixes your issue?

I haven't had time to fully test each permutation.

**Comment by maff** [comment]
Makes the output consistent when phpredis is enabled, but yields errors in standalone mode. Still, the result of the standalone version differs from the phpredis one (numeric vs associative). I think the library should return the same structure in both modes as otherwise clients need to handle the responses returned differently depending on the mode. The results for #86 (shortened paths for readability):

## Redis disabled

    $ php credis-test.php
    DEBUG: credis version: dev-hmget@755b2c02045fd54f07f9041573528038afde5b23
    DEBUG: The Redis extension is not loaded

    credis: simple HMGET
    PHP Warning:  array_combine(): Both parameters should have an equal number of elements in vendor/colinmollenhour/credis/Client.php on line 1355
    PHP Stack trace:
    PHP   1. {main}() credis-test.php:0
    PHP   2. Credis_Client->hMGet() credis-test.php:42
    PHP   3. Credis_Client->__call() credis-test.php:42
    PHP   4. Credis_Client->read_reply() vendor/colinmollenhour/credis/Client.php:998
    PHP   5. array_combine() vendor/colinmollenhour/credis/Client.php:1355

    Warning: array_combine(): Both parameters should have an equal number of elements in vendor/colinmollenhour/credis/Client.php on line 1355

    Call Stack:
        0.0005     350456   1. {main}() credis-test.php:0
        0.0194     363320   2. Credis_Client->hMGet() credis-test.php:42
        0.0194     363696   3. Credis_Client->__call() credis-test.php:42
        0.0198     373984   4. Credis_Client->read_reply() vendor/colinmollenhour/credis/Client.php:998
        0.0198     374520   5. array_combine() vendor/colinmollenhour/credis/Client.php:1355


    credis: pipeline HMGET
    PHP Notice:  Undefined variable: trackArgInPipeline in vendor/colinmollenhour/credis/Client.php on line 974
    PHP Stack trace:
    PHP   1. {main}() credis-test.php:0
    PHP   2. Credis_Client->multi() credis-test.php:48
    PHP   3. Credis_Client->__call() credis-test.php:48

    Notice: Undefined variable: trackArgInPipeline in vendor/colinmollenhour/credis/Client.php on line 974

    Call Stack:
        0.0005     350456   1. {main}() credis-test.php:0
        0.0238     372856   2. Credis_Client->multi() credis-test.php:48
        0.0239     372912   3. Credis_Client->__call() credis-test.php:48

    PHP Notice:  Undefined variable: trackArgInPipeline in vendor/colinmollenhour/credis/Client.php on line 974
    PHP Stack trace:
    PHP   1. {main}() credis-test.php:0
    PHP   2. Credis_Client->hMGet() credis-test.php:49
    PHP   3. Credis_Client->__call() credis-test.php:49

    Notice: Undefined variable: trackArgInPipeline in vendor/colinmollenhour/credis/Client.php on line 974

    Call Stack:
        0.0005     350456   1. {main}() credis-test.php:0
        0.0267     373648   2. Credis_Client->hMGet() credis-test.php:49
        0.0267     374024   3. Credis_Client->__call() credis-test.php:49

    Array
    (
        [0] => Hello
        [1] => World
    )

## Redis enabled

    $ php -d extension=redis.so credis-test.php
    DEBUG: credis version: dev-hmget@755b2c02045fd54f07f9041573528038afde5b23
    DEBUG: The Redis extension is loaded

    phpredis: simple HMGET
    Array
    (
        [field1] => Hello
        [field2] => World
    )

    phpredis: pipeline HMGET
    Array
    (
        [field1] => Hello
        [field2] => World
    )

    credis: simple HMGET
    Array
    (
        [field1] => Hello
        [field2] => World
    )

    credis: pipeline HMGET
    Array
    (
        [field1] => Hello
        [field2] => World
    )

**Comment by Xon** [comment]
@maff I've had some time today and I believe I've fixed the bugs.

**Comment by Xon** [comment]
@maff latest master should have a consistent HMGET implementation. Just working on identifying why one of the tests crashes when using phpredis & pubsub

**Comment by maff** [comment]
@Xon latest master still gives me inconsistent results (see pipeline without phpredis).

## Redis disabled

    $ php credis-test.php
    DEBUG: credis version: dev-master@e0a208d964d8307a962e2616b868c82c77366325
    DEBUG: The Redis extension is not loaded

    credis: simple HMGET
    Array
    (
        [field1] => Hello
        [field2] => World
    )

    credis: pipeline HMGET
    Array
    (
        [0] => Hello
        [1] => World
    )

## Redis enabled

    $ php -dextension=redis.so credis-test.php
    DEBUG: credis version: dev-master@e0a208d964d8307a962e2616b868c82c77366325
    DEBUG: The Redis extension is loaded

    phpredis: simple HMGET
    Array
    (
        [field1] => Hello
        [field2] => World
    )

    phpredis: pipeline HMGET
    Array
    (
        [field1] => Hello
        [field2] => World
    )

    credis: simple HMGET
    Array
    (
        [field1] => Hello
        [field2] => World
    )

    credis: pipeline HMGET
    Array
    (
        [field1] => Hello
        [field2] => World
    )

**Comment by Xon** [comment]
@maff Thanks, I'm adding a bunch more test cases

The issue is; ``` pipeline() ``` and ```pipeline()->multi()``` behave differently when ```exec()``` is called.

This means a bunch of post-processing is missing for some other commands as well;
- config
- hgetall
- info
- ttl

**Comment by Xon** [comment]
@maff https://github.com/colinmollenhour/credis/pull/89 should now contain a number of fixes & vastly more consistent interface for the standalone backend vs phpredis.

**Comment by maff** [comment]
@Xon looks good, now all variants return the associative response as phpredis does. Is this going to be released as new major version? The changed behaviour might break existing implementations expecting the a indexed result.

**Comment by Xon** [comment]
It is up to @colinmollenhour to version stamp any changes, but yeah this isn't a point-release bump.

I'ld prefer not to write a compatibility shim for this.

**Comment by colinmollenhour** [comment]
In retrospect I think the new behavior should have been added as a new method like `hmGetAssoc` or something but it seems the dust has settled now..
