### ISSUE TITLE
PHPUnit Segmentation Fault

### ISSUE THREAD

**Issue by colinmollenhour** [colinmollenhour/credis#87]
I don't know if this is an issue with PHPUnit or the phpredis extension, but the Travis CI tests for PHP 7.0, 7.1 and 7.2 all fail with a segfault..

https://travis-ci.org/colinmollenhour/credis/jobs/278272942#L602

I'm not going to address this for now but if anyone has any ideas or wants to investigate further it would be much appreciated!

**Comment by Xon** [comment]
It is the testPubsub which is reliably blowing up on; https://github.com/colinmollenhour/credis/blob/18e27389b50f7dddb0e423f934b554b8334c4839/tests/CredisTest.php#L321

**Comment by Xon** [comment]
Disabling the testPubsub test and the CredisTest doesn't crash.

**Comment by Xon** [comment]
Yup, testPubsub with phpredis v3.1.3 is what s breaking it

**Comment by Xon** [comment]
Ok, what the hell.

Calling assertEquals in the catch() block with phpredis blows it up. But only in that combination

**Comment by colinmollenhour** [comment]
Does it work on an older version of phpredis?

**Comment by Xon** [comment]
The IUS repo I'm using doesn't have older versions. I managed to reproduce this with just the pubsub test and another empty test. Directly calling phpredis appears to work, so perhaps something is getting confused on the way in?

**Comment by Xon** [comment]
I've created a more minimal test example; https://github.com/Xon/credis/tree/pubsub

**Comment by Xon** [comment]
after investigation this looks to be fixed in phpredis 3.1.4, the RC have some breaking changes that look to be rerolled back. So hopefully it'll be released "soon". I've opened another PR with more unit-test fixes.

**Comment by colinmollenhour** [comment]
So I take it you have tried building with this?

```
  install:
    - yes '' | pecl install -f redis-3.1.4RC3
```

**Comment by Xon** [comment]
@colinmollenhour I manually compiled from git branch, but that should be identical.

**Comment by colinmollenhour** [comment]
Without a deep dive it seems everything passes with this modification to .travis.yml (tested via Travis "Trigger Build" feature): https://travis-ci.org/colinmollenhour/credis/builds/279807178
