### ISSUE TITLE
stream_socket_client() - PHP 7.0.14 - Connection timed out

### ISSUE THREAD

**Issue by rpgarcia** [colinmollenhour/credis#98]
Hi guys!, I have a problem and I can't understand what is due, can you help me please?

The problem is that for some reason, sometimes, I get the following message:
`stream_socket_client(): unable to connect to tcp://10.1.101.37:6379 (Connection timed out) in /home/user/app/vendor/colinmollenhour/credis/Client.php:428`,
and I don't know why?

Ubuntu version: 14.04
PHP Version: 7.0.14. I'm not using persistent connections, Will it have something to do?

The maxclients in redis, is configured in 10 thousand and the maximum that I have of connections, is 3 thousand, therefore I understand that it is not a matter of which I am left without available connections.

Any idea?

**Comment by colinmollenhour** [comment]
That's a lot of connections, are you sure you need so many? Perhaps there are some ulimit or sysctl limitations? I'm sorry, this really isn't the place for such questions unless you suspect there is a bug to be fixed or feature to be added.
